version: "3.8"

services:
  merge-blob:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10007:10007"
      - "9007:9007"
      - "8007:8007"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - IP=host.docker.internal
    restart: always
    stdin_open: true
    tty: true