package constant

type HTTP_METHOD string

const (
	GET_HTTP    HTTP_METHOD = "GET"
	POST_HTTP   HTTP_METHOD = "POST"
	PUT_HTTP    HTTP_METHOD = "PUT"
	PATCH_HTTP  HTTP_METHOD = "PATCH"
	DELETE_HTTP HTTP_METHOD = "DELETE"
)
